apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
  namespace: nginx-demo
  labels:
    app: nginx-demo
spec:
  ports:
    - port: 34343
      targetPort: 80
  selector:
    app: nginx-demo
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-demo-deployment
  namespace: nginx-demo
  labels:
    app: nginx-demo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - image: otterwerks/kubernetes-jenkins-nginx-demo
        name: nginx-demo
        ports:
        - containerPort: 80
          name: nginx
